version: '3.8'

services:
  web:
    build: ./web-app
    ports:
      - '3000:3000'
    environment:
      POSTGRES_PASSWORD: my_pg_password
    depends_on:
      - db
  db:
    image: postgres:16.0
    environment:
      POSTGRES_PASSWORD: my_pg_password
      PGDATA: /pg-data
    volumes:
      - './pg-data:/pg-data'
