version: '3.8'

services:
  web:
    build: ./web-app
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_PASSWORD
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:16.0
    environment:
      - POSTGRES_PASSWORD
      - PGDATA=/pg-data
    restart: unless-stopped
    volumes:
      - './pg-data:/pg-data'
